version: '3.8'

services:
  discord-bot:
    container_name: 'mimic-st-bot'
    environment:
      - TOKEN_DISCORD=${TOKEN_DISCORD}
    build: .
    ports:
      - "90:8090"
      - "453:8543"
    networks:
      - mimic-st-network
networks:
  mimic-st-network:
    name: "mimic-st-network"