version: '3.8'

services:
  discord-bot:
    container_name: 'mimic-storyteller-bot'
    environment:
      - TOKEN_DISCORD=${TOKEN_DISCORD}
    build: .
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - mimic-network
networks:
  mimic-network:
        name: "mimic-storyteller-network"